const products = [
    {
      id: 1,
      name: "Wireless Headphones",
      image: "/images/headphones.jpg",
      price: 1999,
      originalPrice: 3999,
      discount: 50,
      rating: 4.5,
      reviews: 2300,
      deliveryDate: "Fri, 9 Feb",
    },
    {
      id: 2,
      name: "Smartwatch",
      image: "/images/smartwatch.jpg",
      price: 2499,
      originalPrice: 4999,
      discount: 50,
      rating: 4.3,
      reviews: 1800,
      deliveryDate: "Sat, 10 Feb",
    },
    {
      id: 3,
      name: "Gaming Mouse",
      image: "/images/mouse.jpg",
      price: 899,
      originalPrice: 1599,
      discount: 44,
      rating: 4.7,
      reviews: 1200,
      deliveryDate: "Sun, 11 Feb",
    },
    {
      id: 4,
      name: "Mechanical Keyboard",
      image: "/images/keyboard.jpg",
      price: 2799,
      originalPrice: 4999,
      discount: 44,
      rating: 4.6,
      reviews: 950,
      deliveryDate: "Mon, 12 Feb",
    },
    {
      id: 1,
      name: "Wireless Headphones",
      image: "/images/headphones.jpg",
      price: 1999,
      originalPrice: 3999,
      discount: 50,
      rating: 4.5,
      reviews: 2300,
      deliveryDate: "Fri, 9 Feb",
    },
    {
      id: 2,
      name: "Smartwatch",
      image: "/images/smartwatch.jpg",
      price: 2499,
      originalPrice: 4999,
      discount: 50,
      rating: 4.3,
      reviews: 1800,
      deliveryDate: "Sat, 10 Feb",
    },
    {
      id: 3,
      name: "Gaming Mouse",
      image: "/images/mouse.jpg",
      price: 899,
      originalPrice: 1599,
      discount: 44,
      rating: 4.7,
      reviews: 1200,
      deliveryDate: "Sun, 11 Feb",
    },
    {
      id: 4,
      name: "Mechanical Keyboard",
      image: "/images/keyboard.jpg",
      price: 2799,
      originalPrice: 4999,
      discount: 44,
      rating: 4.6,
      reviews: 950,
      deliveryDate: "Mon, 12 Feb",
    },
  ];
  
  export default products;
  